# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_add', models.GenericIPAddressField()),
                ('port', models.PositiveSmallIntegerField()),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
    ]
